import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import "./editor.css";
import SnackbarProvider from "@/components/global/SnackbarProvider";
import { LoaderContainer } from "react-global-loader";
import { Suspense } from "react";
// import { ThemeProvider } from "@/context/ThemeContext";
// import { SidebarProvider } from "@/context/SidebarContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} dark:bg-gray-900`}>
        <LoaderContainer align='flex-start'>
          <div className="absolute top-0 left-0 bg-gray-100/10 h-[100vh] w-[100vw] z-999 ">
            <div className="loader"></div>
          </div>
        </LoaderContainer>
        <SnackbarProvider>
          <Suspense>
          {children}
          </Suspense>
        </SnackbarProvider>
      </body>
    </html>
  );
}
